### ISSUE TITLE
Yellow doge on white background

### ISSUE THREAD

**Issue by morzzz007** [laasli/doge-node#1]
Setting the console output color to yellow prints a nearly insivible doge on white terminal backgrounds. I think it would be a better idea to use the default color unless a parameter/config object with colors passed to the suchDogeMuchAscii() function.

![screen shot 2015-11-10 at 11 08 36](https://cloud.githubusercontent.com/assets/4503564/11059709/827f337a-879b-11e5-8443-9adb83f148b7.png)

**Comment by kfrendrich** [comment]
+1 pls use inverse colors ;)

**Comment by nandordevai** [comment]
:+1:

**Comment by dubovinszky** [comment]
+1

**Comment by laszlo-berces-epam** [comment]
Thanks for coming up with this idea, @morzzz007 I will soon ship a hotfix for this.

**Comment by laasli** [comment]
I've made an update, you can now pass a config object to **suchDogeMuchAscii()** function. The passable object looks like this:

```
{
  color: 'yellowBright',
  cls: true
}
```

(Note that these are the default values of the object.)

For the available color options please refer to: https://github.com/medikoo/cli-color#colors .

And since it was a new feature, please update your dependency to **163.1.3**.

**Comment by morzzz007** [comment]
I can't test it right now, but if there is a default yellow bright color set it doesn't solve our problems, because I have to pre-check the terminal's background color and set the doge's color accordingly, but I just want to fire and forget it. How about when I don't provide a color it remains the default without modifying the cli colors?

**Comment by laasli** [comment]
Thanks for pointing that out, @morzzz007 i will change the code according to this.

**Comment by laasli** [comment]
Made the change according to our conversation please check :)

**Comment by morzzz007** [comment]
Thank you, it works like a charm!
